# Generated by Django 4.2 on 2024-09-27 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(db_index=True, editable=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='note_images/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('list', 'List')], max_length=5)),
                ('color', models.CharField(choices=[('none', 'None'), ('coral', 'Coral'), ('peach', 'Peach'), ('sand', 'Sand'), ('sage', 'Sage'), ('fog', 'Fog'), ('storm', 'Storm'), ('dusk', 'Dusk')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('pinned', 'Pinned'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='normal', max_length=10)),
            ],
            options={
                'ordering': ['-status', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='notes.note')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
